version: "3.9"
services:
  postgres:
    image: postgres:15-bullseye
    platform: linux/amd64
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.docker-storage/postgres:/var/lib/postgresql/data
